import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import ToggleTheme from '@/components/ToggleTheme'
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <main className="flex h-screen w-full font-inter">
            <ToggleTheme />
            <div className="container">{children}</div>
        </main>
    )
}
