import type { Metadata } from 'next'
import MobileHeader from '@/components/MobileHeader'

import ToggleTheme from '@/components/ToggleTheme'
import Sidebar from '@/components/Sidebar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <Sidebar />
            <main className="flex flex-col w-full font-inter">
                <MobileHeader />

                {children}
            </main>
        </>
    )
}
